name: "CI: Build Test"

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        qt_version: [5.12.6, 5.13.2, 5.14.0, 5.15.0]
        platform: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt_version }}

    - name: cmake
      run: cmake .

    - name: cmake build
      run: cmake --build .

    - name: Build example - basic (cmake)
      working-directory: examples/basic/
      run: |
        cmake .
        cmake --build .

    - name: Build example - calculator (cmake)
      working-directory: examples/calculator/
      run: |
        cmake .
        cmake --build .

    - name: Build example - sending_arguments (cmake)
      working-directory: examples/sending_arguments/
      run: |
        cmake .
        cmake --build .
