set_target_properties(lemon
    PROPERTIES
    MACOSX_BUNDLE TRUE
    MACOSX_BUNDLE_INFO_PLIST "${CMAKE_SOURCE_DIR}/assets/MacOSXInfo.plist.in"
    MACOSX_BUNDLE_BUNDLE_NAME "LemonLime"
    MACOSX_BUNDLE_COPYRIGHT "Copyright (c) 2019-2024 Project LemonLime"
    MACOSX_BUNDLE_BUNDLE_VERSION ${VERSION_STRING}
    MACOSX_BUNDLE_LONG_VERSION_STRING ${VERSION_STRING}
    MACOSX_BUNDLE_SHORT_VERSION_STRING ${VERSION_STRING}
    MACOSX_BUNDLE_GUI_IDENTIFIER "com.github.lemonlime"
    )
