# ==================================================================================
# Lemon UI
# ==================================================================================

set(LEMON_BASEDIR_UI ${CMAKE_SOURCE_DIR}/src)

set(LEMON_UI_SOURCES
    ${LEMON_BASEDIR_UI}/main.cpp
    ${LEMON_BASEDIR_UI}/exttestcasemodifier.cpp
    ${LEMON_BASEDIR_UI}/exttestcasemodifierdialog.cpp
    ${LEMON_BASEDIR_UI}/exttestcasetable.cpp
    ${LEMON_BASEDIR_UI}/exttestcaseupdaterdialog.cpp
    ${LEMON_BASEDIR_UI}/visualmainsettings.cpp
    ${LEMON_BASEDIR_UI}/visualsettings.cpp
    ${LEMON_BASEDIR_UI}/themeeditdialog.cpp
    ${LEMON_BASEDIR_UI}/lemon.cpp
    ${LEMON_BASEDIR_UI}/filelineedit.cpp
    ${LEMON_BASEDIR_UI}/summarytree.cpp
    ${LEMON_BASEDIR_UI}/taskeditwidget.cpp
    ${LEMON_BASEDIR_UI}/testcaseeditwidget.cpp
    ${LEMON_BASEDIR_UI}/generalsettings.cpp
    ${LEMON_BASEDIR_UI}/compilersettings.cpp
    ${LEMON_BASEDIR_UI}/addtestcaseswizard.cpp
    ${LEMON_BASEDIR_UI}/judgingdialog.cpp
    ${LEMON_BASEDIR_UI}/optionsdialog.cpp
    ${LEMON_BASEDIR_UI}/resultviewer.cpp
    ${LEMON_BASEDIR_UI}/detaildialog.cpp
    ${LEMON_BASEDIR_UI}/newcontestwidget.cpp
    ${LEMON_BASEDIR_UI}/opencontestwidget.cpp
    ${LEMON_BASEDIR_UI}/newcontestdialog.cpp
    ${LEMON_BASEDIR_UI}/opencontestdialog.cpp
    ${LEMON_BASEDIR_UI}/welcomedialog.cpp
    ${LEMON_BASEDIR_UI}/addtaskdialog.cpp
    ${LEMON_BASEDIR_UI}/advancedcompilersettingsdialog.cpp
    ${LEMON_BASEDIR_UI}/environmentvariablesdialog.cpp
    ${LEMON_BASEDIR_UI}/editvariabledialog.cpp
    ${LEMON_BASEDIR_UI}/addcompilerwizard.cpp
    ${LEMON_BASEDIR_UI}/statisticsbrowser.cpp
    ${LEMON_BASEDIR_UI}/component/exportutil/exportutil.cpp
    )

set(LEMON_UI_HEADERS
    ${LEMON_BASEDIR_UI}/lemon.h
    ${LEMON_BASEDIR_UI}/exttestcasemodifier.h
    ${LEMON_BASEDIR_UI}/exttestcasemodifierdialog.h
    ${LEMON_BASEDIR_UI}/exttestcasetable.h
    ${LEMON_BASEDIR_UI}/exttestcaseupdaterdialog.h
    ${LEMON_BASEDIR_UI}/visualmainsettings.h
    ${LEMON_BASEDIR_UI}/visualsettings.h
    ${LEMON_BASEDIR_UI}/themeeditdialog.h
    ${LEMON_BASEDIR_UI}/filelineedit.h
    ${LEMON_BASEDIR_UI}/summarytree.h
    ${LEMON_BASEDIR_UI}/taskeditwidget.h
    ${LEMON_BASEDIR_UI}/testcaseeditwidget.h
    ${LEMON_BASEDIR_UI}/generalsettings.h
    ${LEMON_BASEDIR_UI}/compilersettings.h
    ${LEMON_BASEDIR_UI}/addtestcaseswizard.h
    ${LEMON_BASEDIR_UI}/judgingdialog.h
    ${LEMON_BASEDIR_UI}/optionsdialog.h
    ${LEMON_BASEDIR_UI}/resultviewer.h
    ${LEMON_BASEDIR_UI}/detaildialog.h
    ${LEMON_BASEDIR_UI}/newcontestwidget.h
    ${LEMON_BASEDIR_UI}/opencontestwidget.h
    ${LEMON_BASEDIR_UI}/newcontestdialog.h
    ${LEMON_BASEDIR_UI}/opencontestdialog.h
    ${LEMON_BASEDIR_UI}/welcomedialog.h
    ${LEMON_BASEDIR_UI}/addtaskdialog.h
    ${LEMON_BASEDIR_UI}/advancedcompilersettingsdialog.h
    ${LEMON_BASEDIR_UI}/environmentvariablesdialog.h
    ${LEMON_BASEDIR_UI}/editvariabledialog.h
    ${LEMON_BASEDIR_UI}/addcompilerwizard.h
    ${LEMON_BASEDIR_UI}/statisticsbrowser.h
    ${LEMON_BASEDIR_UI}/component/exportutil/exportutil.h
    )

set(LEMON_UI_FORMS
    ${LEMON_BASEDIR_UI}/forms/lemon.ui
    ${LEMON_BASEDIR_UI}/forms/exttestcasemodifierdialog.ui
    ${LEMON_BASEDIR_UI}/forms/exttestcasemodifier.ui
    ${LEMON_BASEDIR_UI}/forms/exttestcaseupdaterdialog.ui
    ${LEMON_BASEDIR_UI}/forms/taskeditwidget.ui
    ${LEMON_BASEDIR_UI}/forms/testcaseeditwidget.ui
    ${LEMON_BASEDIR_UI}/forms/generalsettings.ui
    ${LEMON_BASEDIR_UI}/forms/compilersettings.ui
    ${LEMON_BASEDIR_UI}/forms/addtestcaseswizard.ui
    ${LEMON_BASEDIR_UI}/forms/judgingdialog.ui
    ${LEMON_BASEDIR_UI}/forms/optionsdialog.ui
    ${LEMON_BASEDIR_UI}/forms/detaildialog.ui
    ${LEMON_BASEDIR_UI}/forms/newcontestwidget.ui
    ${LEMON_BASEDIR_UI}/forms/opencontestwidget.ui
    ${LEMON_BASEDIR_UI}/forms/newcontestdialog.ui
    ${LEMON_BASEDIR_UI}/forms/opencontestdialog.ui
    ${LEMON_BASEDIR_UI}/forms/visualmainsettings.ui
    ${LEMON_BASEDIR_UI}/forms/visualsettings.ui
    ${LEMON_BASEDIR_UI}/forms/themeeditdialog.ui
    ${LEMON_BASEDIR_UI}/forms/welcomedialog.ui
    ${LEMON_BASEDIR_UI}/forms/addtaskdialog.ui
    ${LEMON_BASEDIR_UI}/forms/advancedcompilersettingsdialog.ui
    ${LEMON_BASEDIR_UI}/forms/environmentvariablesdialog.ui
    ${LEMON_BASEDIR_UI}/forms/editvariabledialog.ui
    ${LEMON_BASEDIR_UI}/forms/addcompilerwizard.ui
    ${LEMON_BASEDIR_UI}/forms/statisticsbrowser.ui
    )
