name: "Check Clang Format"

on: [push, pull_request]

jobs:
  formatting-check:
    name: "Check Clang Format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jidicula/clang-format-action@v4.18.0
        with:
          clang-format-version: "21"
          check-path: "src"
